main: net.brysonsteck.Resurrection.Resurrection
name: Resurrection
author: 'Bryson Steck'
version: '0.1 beta'
commands:
  about:
    description: Displays information about Resurrection.
    permission: op
    usage: /about

  timecheck:
    description: Displays the remaining time before the player (or specified player) is resurrected.
    usage: /timecheck [PLAYER NAME]

  resurrect:
    description: Manually resurrects a player.
    permission: op
    usage: /resurrect PLAYER_NAME