main: net.brysonsteck.Resurrection
name: Resurrection
author: 'Bryson Steck'
version: '0.0.1 alpha'
commands:
  about:
    description: Displays information about Resurrection.
    permission: op
    usage: /about