main: net.brysonsteck.Resurrection.Resurrection
name: Resurrection
author: 'Bryson Steck'
version: '1.2'
website: https://brysonsteck.net/resurrection.html
description: Makes players wait large amounts of time before respawning!
database: false
api-version: 1.16

commands:
  about:
    description: Displays information about Resurrection.
    permission: op
    usage: /about

  howlong:
    description: Displays the remaining time before the player (or specified player) is resurrected.
    usage: /howlong [PLAYER_NAME]
    aliases: [timeleft]

  resurrect:
    description: Manually resurrects a player.
    permission: op
    usage: /resurrect PLAYER_NAME

  bug:
    description: Displays contact info if you encounter a bug using Resurrection.
    usage: /bug

  source:
    description: Displays info about the source code of Resurrection.
    usage: /source
  
  dead:
    description: Displays all players who are awaiting resurrection.
    usage: /dead